package com.poc.com.poc.dynamo.entity;

import java.util.Date;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIndexRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Pessoa")
public class PessoaEntity {

	@DynamoDBHashKey(attributeName = "id")
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute(attributeName="nome")
	private String nome;

	@DynamoDBIndexHashKey(globalSecondaryIndexName = "idadeIndex",attributeName = "idade")
	@DynamoDBAttribute(attributeName="idade")
	private Integer idade;


	
    @DynamoDBIndexRangeKey(globalSecondaryIndexName = "idadeIndex",attributeName = "dataDeInclusao")
	//@DynamoDBIndexHashKey(globalSecondaryIndexName = "dataIndex",attributeName = "dataDeInclusao")
	@DynamoDBAttribute(attributeName="dataDeInclusao")
    private Long dataDeInclusao;

	public PessoaEntity(String nome, int idade) {
		this.nome = nome;
		this.idade = idade;
		this.dataDeInclusao = new Date().getTime();
	}

	public PessoaEntity() {

	}

	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public Integer getIdade() {
		return idade;
	}

	public void setIdade(Integer idade) {
		this.idade = idade;
	}

	
	@Override
	public String toString() {
		return "PessoaEntity [id=" + id + ", nome=" + nome + ", idade=" + idade + ", dataDeInclusao=" + new Date(dataDeInclusao)
				+ "]";
	}

	public Long getDataDeInclusao() {
		return dataDeInclusao;
	}

	public void setDataDeInclusao(Long dataDeInclusao) {
		this.dataDeInclusao = dataDeInclusao;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((dataDeInclusao == null) ? 0 : dataDeInclusao.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((idade == null) ? 0 : idade.hashCode());
		result = prime * result + ((nome == null) ? 0 : nome.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		PessoaEntity other = (PessoaEntity) obj;
		if (dataDeInclusao == null) {
			if (other.dataDeInclusao != null)
				return false;
		} else if (!dataDeInclusao.equals(other.dataDeInclusao))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (idade == null) {
			if (other.idade != null)
				return false;
		} else if (!idade.equals(other.idade))
			return false;
		if (nome == null) {
			if (other.nome != null)
				return false;
		} else if (!nome.equals(other.nome))
			return false;
		return true;
	}

	
	
}
